# Generated by Django 3.0.7 on 2020-07-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
        ),
    ]
